# Generated by Django 4.2.16 on 2024-10-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_id", models.IntegerField()),
                ("question", models.TextField()),
                ("option_1", models.TextField()),
                ("option_2", models.TextField()),
                ("option_3", models.TextField()),
                ("option_4", models.TextField()),
                ("correct_option_number", models.IntegerField()),
                ("correct_answer", models.TextField()),
                ("solution", models.TextField()),
            ],
        ),
    ]
